
-- Seed the items table with 300+ items across 10 categories
INSERT INTO items (name, description, item_type, price, weight, damage_dice, armor_bonus, required_level, is_magical) VALUES
-- Weapons (30 items)
('Dagger', 'A simple, sharp blade.', 'Weapon', 2, 1.0, '1d4', 0, 1, 0),
('Shortsword', 'A lightweight sword perfect for quick strikes.', 'Weapon', 10, 2.0, '1d6', 0, 1, 0),
('Longsword', 'A versatile blade favored by many warriors.', 'Weapon', 15, 3.0, '1d8', 0, 1, 0),
('Greatsword', 'A massive two-handed blade.', 'Weapon', 50, 6.0, '2d6', 0, 3, 0),
('Rapier', 'An elegant thrusting sword.', 'Weapon', 25, 2.0, '1d8', 0, 2, 0),
('Scimitar', 'A curved blade from distant lands.', 'Weapon', 25, 3.0, '1d6', 0, 2, 0),
('Handaxe', 'A small, balanced throwing axe.', 'Weapon', 5, 2.0, '1d6', 0, 1, 0),
('Battleaxe', 'A heavy axe designed for combat.', 'Weapon', 10, 4.0, '1d8', 0, 2, 0),
('Greataxe', 'A massive two-handed axe.', 'Weapon', 30, 7.0, '1d12', 0, 3, 0),
('Mace', 'A heavy club with a spiked head.', 'Weapon', 5, 4.0, '1d6', 0, 1, 0),
('Warhammer', 'A balanced hammer designed for war.', 'Weapon', 15, 2.0, '1d8', 0, 2, 0),
('Maul', 'A massive two-handed hammer.', 'Weapon', 10, 10.0, '2d6', 0, 3, 0),
('Spear', 'A long pole weapon with a sharp point.', 'Weapon', 1, 3.0, '1d6', 0, 1, 0),
('Pike', 'An extremely long spear.', 'Weapon', 5, 18.0, '1d10', 0, 2, 0),
('Glaive', 'A pole weapon with a curved blade.', 'Weapon', 20, 6.0, '1d10', 0, 3, 0),
('Shortbow', 'A compact bow for hunting.', 'Weapon', 25, 2.0, '1d6', 0, 1, 0),
('Longbow', 'A powerful bow with long range.', 'Weapon', 50, 2.0, '1d8', 0, 2, 0),
('Light Crossbow', 'A mechanical bow easy to use.', 'Weapon', 25, 5.0, '1d8', 0, 1, 0),
('Heavy Crossbow', 'A powerful crossbow requiring strength.', 'Weapon', 50, 18.0, '1d10', 0, 3, 0),
('Sling', 'A simple projectile weapon.', 'Weapon', 0, 0.0, '1d4', 0, 1, 0),
('Whip', 'A flexible weapon with reach.', 'Weapon', 2, 3.0, '1d4', 0, 1, 0),
('Trident', 'A three-pronged spear from the sea.', 'Weapon', 5, 4.0, '1d6', 0, 2, 0),
('Net', 'Used to entangle enemies.', 'Weapon', 1, 3.0, '', 0, 1, 0),
('Flaming Sword', 'A magical blade wreathed in fire.', 'Weapon', 500, 3.0, '1d8+1d6', 0, 5, 1),
('Frost Dagger', 'A dagger that freezes enemies.', 'Weapon', 200, 1.0, '1d4+1d4', 0, 3, 1),
('Thunder Hammer', 'A hammer that creates sonic booms.', 'Weapon', 800, 2.0, '1d8+thunder', 0, 7, 1),
('Vorpal Blade', 'A legendary sword that can decapitate.', 'Weapon', 2000, 3.0, '1d8', 0, 10, 1),
('Dragon Slayer', 'A sword designed to kill dragons.', 'Weapon', 1500, 4.0, '2d6', 0, 8, 1),
('Staff of Power', 'A magical staff crackling with energy.', 'Weapon', 1200, 4.0, '1d6+spell', 0, 6, 1),
('Bow of Seeking', 'Arrows from this bow never miss.', 'Weapon', 1000, 2.0, '1d8+seeking', 0, 5, 1),

-- Armor (30 items)
('Leather Armor', 'Flexible protection made from animal hide.', 'Armor', 10, 10.0, '', 1, 1, 0),
('Studded Leather', 'Leather reinforced with metal studs.', 'Armor', 45, 13.0, '', 2, 1, 0),
('Hide Armor', 'Crude armor made from thick animal pelts.', 'Armor', 10, 12.0, '', 2, 1, 0),
('Chain Shirt', 'A shirt of interlocking metal rings.', 'Armor', 50, 20.0, '', 3, 2, 0),
('Scale Mail', 'Armor made from overlapping metal scales.', 'Armor', 50, 45.0, '', 4, 2, 0),
('Breastplate', 'A fitted metal chest piece.', 'Armor', 400, 20.0, '', 4, 3, 0),
('Half Plate', 'Partial plate armor covering vital areas.', 'Armor', 750, 40.0, '', 5, 4, 0),
('Ring Mail', 'Leather armor with sewn-on metal rings.', 'Armor', 30, 40.0, '', 4, 2, 0),
('Chain Mail', 'A suit of interlocked metal rings.', 'Armor', 75, 55.0, '', 6, 3, 0),
('Splint Armor', 'Metal strips riveted to leather backing.', 'Armor', 200, 60.0, '', 7, 4, 0),
('Plate Armor', 'The finest protection money can buy.', 'Armor', 1500, 65.0, '', 8, 5, 0),
('Padded Armor', 'Quilted layers provide basic protection.', 'Armor', 5, 8.0, '', 1, 1, 0),
('Dragon Scale Mail', 'Armor crafted from dragon scales.', 'Armor', 2000, 45.0, '', 6, 7, 1),
('Mithril Chain', 'Exceptionally light magical armor.', 'Armor', 5000, 10.0, '', 5, 8, 1),
('Armor of Invulnerability', 'Legendary armor that deflects attacks.', 'Armor', 8000, 65.0, '', 8, 10, 1),
('Studded Leather +1', 'Magically enhanced studded leather.', 'Armor', 200, 13.0, '', 3, 3, 1),
('Chain Mail +1', 'Magically enhanced chain mail.', 'Armor', 500, 55.0, '', 7, 5, 1),
('Plate Armor +1', 'Magically enhanced plate armor.', 'Armor', 3000, 65.0, '', 9, 7, 1),
('Cloak of Protection', 'A cloak that wards off danger.', 'Armor', 1000, 1.0, '', 1, 4, 1),
('Bracers of Defense', 'Magical bracers that deflect attacks.', 'Armor', 800, 2.0, '', 2, 3, 1),
('Robe of the Archmagi', 'Robes that enhance magical abilities.', 'Armor', 5000, 4.0, '', 5, 9, 1),
('Leather Armor +2', 'Highly enchanted leather armor.', 'Armor', 800, 10.0, '', 3, 6, 1),
('Elven Chain', 'Lightweight armor from elven smiths.', 'Armor', 1200, 20.0, '', 4, 5, 1),
('Demon Armor', 'Sinister armor from the abyss.', 'Armor', 3000, 60.0, '', 7, 8, 1),
('Crystal Armor', 'Translucent armor of pure crystal.', 'Armor', 2500, 30.0, '', 5, 7, 1),
('Shadow Leather', 'Armor that bends light around the wearer.', 'Armor', 1500, 8.0, '', 2, 6, 1),
('Plate of the Phoenix', 'Armor that grants fire immunity.', 'Armor', 10000, 65.0, '', 8, 12, 1),
('Mage Armor Robe', 'Robes that provide magical protection.', 'Armor', 300, 3.0, '', 3, 2, 1),
('Barbarian Hide', 'Primitive but effective protection.', 'Armor', 100, 15.0, '', 3, 2, 0),
('Noble Doublet', 'Fashionable protection for aristocrats.', 'Armor', 500, 5.0, '', 2, 3, 0),

-- Shields (20 items)
('Shield', 'A basic wooden shield.', 'Shield', 10, 6.0, '', 2, 1, 0),
('Buckler', 'A small, light shield.', 'Shield', 5, 3.0, '', 1, 1, 0),
('Tower Shield', 'A massive shield providing full cover.', 'Shield', 30, 15.0, '', 3, 3, 0),
('Shield +1', 'A magically enhanced shield.', 'Shield', 500, 6.0, '', 3, 3, 1),
('Shield +2', 'A highly enchanted shield.', 'Shield', 2000, 6.0, '', 4, 6, 1),
('Shield +3', 'A powerfully enchanted shield.', 'Shield', 8000, 6.0, '', 5, 9, 1),
('Shield of Spell Turning', 'Reflects spells back at casters.', 'Shield', 5000, 6.0, '', 2, 8, 1),
('Shield of Fire Resistance', 'Protects against fire damage.', 'Shield', 1000, 6.0, '', 2, 4, 1),
('Mirror Shield', 'A polished shield that blinds enemies.', 'Shield', 800, 8.0, '', 2, 3, 1),
('Spiked Shield', 'A shield with dangerous spikes.', 'Shield', 25, 8.0, '1d4', 2, 2, 0),
('Animated Shield', 'A shield that fights on its own.', 'Shield', 3000, 6.0, '', 2, 7, 1),
('Dragon Scale Shield', 'Made from ancient dragon scales.', 'Shield', 1500, 6.0, '', 3, 5, 1),
('Crystal Shield', 'A transparent shield of pure crystal.', 'Shield', 1200, 4.0, '', 2, 4, 1),
('Demon Shield', 'A shield forged in the depths of hell.', 'Shield', 2500, 8.0, '', 3, 7, 1),
('Paladin Shield', 'A holy shield blessed by the gods.', 'Shield', 2000, 6.0, '', 3, 6, 1),
('Shadow Shield', 'A shield that absorbs light.', 'Shield', 1800, 5.0, '', 2, 5, 1),
('Storm Shield', 'Crackles with electrical energy.', 'Shield', 2200, 7.0, '', 3, 6, 1),
('Aegis of Warding', 'Legendary shield of protection.', 'Shield', 10000, 6.0, '', 4, 12, 1),
('Moonbeam Shield', 'Glows with silvery light.', 'Shield', 1600, 5.0, '', 2, 5, 1),
('Earthen Bulwark', 'Shield carved from living stone.', 'Shield', 900, 12.0, '', 3, 4, 1),

-- Potions (40 items)
('Healing Potion', 'Restores 2d4+2 hit points.', 'Potion', 50, 0.5, '', 0, 1, 1),
('Greater Healing Potion', 'Restores 4d4+4 hit points.', 'Potion', 200, 0.5, '', 0, 3, 1),
('Superior Healing Potion', 'Restores 8d4+8 hit points.', 'Potion', 500, 0.5, '', 0, 5, 1),
('Supreme Healing Potion', 'Restores 10d4+20 hit points.', 'Potion', 1000, 0.5, '', 0, 8, 1),
('Potion of Strength', 'Increases Strength for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Dexterity', 'Increases Dexterity for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Constitution', 'Increases Constitution for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Intelligence', 'Increases Intelligence for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Wisdom', 'Increases Wisdom for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Charisma', 'Increases Charisma for 1 hour.', 'Potion', 300, 0.5, '', 0, 2, 1),
('Potion of Fire Resistance', 'Grants resistance to fire damage.', 'Potion', 150, 0.5, '', 0, 2, 1),
('Potion of Cold Resistance', 'Grants resistance to cold damage.', 'Potion', 150, 0.5, '', 0, 2, 1),
('Potion of Lightning Resistance', 'Grants resistance to lightning damage.', 'Potion', 150, 0.5, '', 0, 2, 1),
('Potion of Poison Resistance', 'Grants resistance to poison damage.', 'Potion', 100, 0.5, '', 0, 1, 1),
('Potion of Flying', 'Grants the ability to fly for 1 hour.', 'Potion', 500, 0.5, '', 0, 4, 1),
('Potion of Invisibility', 'Grants invisibility for 1 hour.', 'Potion', 400, 0.5, '', 0, 3, 1),
('Potion of Speed', 'Doubles movement speed for 1 minute.', 'Potion', 400, 0.5, '', 0, 3, 1),
('Potion of Giant Strength', 'Grants incredible strength.', 'Potion', 800, 0.5, '', 0, 6, 1),
('Potion of Mind Reading', 'Allows reading thoughts for 10 minutes.', 'Potion', 600, 0.5, '', 0, 4, 1),
('Potion of Water Breathing', 'Breathe underwater for 1 hour.', 'Potion', 100, 0.5, '', 0, 1, 1),
('Potion of Darkvision', 'See in darkness for 8 hours.', 'Potion', 150, 0.5, '', 0, 2, 1),
('Potion of Climbing', 'Climb any surface for 1 hour.', 'Potion', 120, 0.5, '', 0, 1, 1),
('Antidote', 'Cures all poisons immediately.', 'Potion', 50, 0.5, '', 0, 1, 1),
('Potion of Heroism', 'Grants bravery and combat prowess.', 'Potion', 250, 0.5, '', 0, 3, 1),
('Potion of Growth', 'Doubles size for 1 hour.', 'Potion', 300, 0.5, '', 0, 3, 1),
('Potion of Diminution', 'Halves size for 1 hour.', 'Potion', 300, 0.5, '', 0, 3, 1),
('Potion of Gaseous Form', 'Become gaseous for 1 hour.', 'Potion', 400, 0.5, '', 0, 4, 1),
('Potion of Animal Friendship', 'Animals become friendly for 24 hours.', 'Potion', 100, 0.5, '', 0, 1, 1),
('Potion of Clairvoyance', 'See distant locations for 10 minutes.', 'Potion', 500, 0.5, '', 0, 4, 1),
('Potion of Longevity', 'Reverses aging effects.', 'Potion', 2000, 0.5, '', 0, 8, 1),
('Potion of Vitality', 'Removes exhaustion and disease.', 'Potion', 400, 0.5, '', 0, 3, 1),
('Elixir of Health', 'Cures all diseases and conditions.', 'Potion', 600, 0.5, '', 0, 5, 1),
('Potion of Hill Giant Strength', 'Grants the strength of a hill giant.', 'Potion', 500, 0.5, '', 0, 4, 1),
('Potion of Storm Giant Strength', 'Grants the strength of a storm giant.', 'Potion', 2000, 0.5, '', 0, 8, 1),
('Potion of Invulnerability', 'Grants immunity to damage for 1 minute.', 'Potion', 5000, 0.5, '', 0, 10, 1),
('Potion of Supreme Healing', 'Fully heals all wounds.', 'Potion', 2000, 0.5, '', 0, 8, 1),
('Oil of Etherealness', 'Become ethereal for 1 hour.', 'Potion', 1000, 0.5, '', 0, 6, 1),
('Potion of Truesight', 'See through all illusions for 1 hour.', 'Potion', 800, 0.5, '', 0, 5, 1),
('Potion of Maximum Power', 'All dice rolls are maximum for 1 minute.', 'Potion', 3000, 0.5, '', 0, 9, 1),
('Divine Elixir', 'Blessed potion that heals and protects.', 'Potion', 1500, 0.5, '', 0, 7, 1),

-- Scrolls (30 items) 
('Scroll of Magic Missile', 'Casts Magic Missile spell.', 'Scroll', 50, 0.0, '', 0, 1, 1),
('Scroll of Fireball', 'Casts Fireball spell.', 'Scroll', 150, 0.0, '', 0, 3, 1),
('Scroll of Lightning Bolt', 'Casts Lightning Bolt spell.', 'Scroll', 150, 0.0, '', 0, 3, 1),
('Scroll of Cure Wounds', 'Casts Cure Wounds spell.', 'Scroll', 25, 0.0, '', 0, 1, 1),
('Scroll of Identify', 'Reveals magical properties of items.', 'Scroll', 100, 0.0, '', 0, 1, 1),
('Scroll of Teleport', 'Instantly travel to known location.', 'Scroll', 500, 0.0, '', 0, 5, 1),
('Scroll of Resurrection', 'Brings back the dead.', 'Scroll', 2000, 0.0, '', 0, 9, 1),
('Scroll of Invisibility', 'Casts Invisibility spell.', 'Scroll', 100, 0.0, '', 0, 2, 1),
('Scroll of Fly', 'Grants flight for 10 minutes.', 'Scroll', 200, 0.0, '', 0, 3, 1),
('Scroll of Shield', 'Provides magical protection.', 'Scroll', 25, 0.0, '', 0, 1, 1),
('Scroll of Sleep', 'Puts enemies to sleep.', 'Scroll', 50, 0.0, '', 0, 1, 1),
('Scroll of Charm Person', 'Charms a humanoid.', 'Scroll', 50, 0.0, '', 0, 1, 1),
('Scroll of Web', 'Creates sticky webs.', 'Scroll', 100, 0.0, '', 0, 2, 1),
('Scroll of Haste', 'Doubles speed and actions.', 'Scroll', 200, 0.0, '', 0, 3, 1),
('Scroll of Slow', 'Slows enemy movement and actions.', 'Scroll', 200, 0.0, '', 0, 3, 1),
('Scroll of Dispel Magic', 'Removes magical effects.', 'Scroll', 150, 0.0, '', 0, 3, 1),
('Scroll of Counterspell', 'Stops spells from being cast.', 'Scroll', 150, 0.0, '', 0, 3, 1),
('Scroll of Polymorph', 'Transforms target into beast.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Greater Invisibility', 'Advanced invisibility spell.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Ice Storm', 'Creates devastating ice storm.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Wall of Fire', 'Creates a wall of flames.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Confusion', 'Confuses multiple enemies.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Dimension Door', 'Short-range teleportation.', 'Scroll', 300, 0.0, '', 0, 4, 1),
('Scroll of Cone of Cold', 'Devastating frost attack.', 'Scroll', 400, 0.0, '', 0, 5, 1),
('Scroll of Dominate Person', 'Control a humanoid.', 'Scroll', 400, 0.0, '', 0, 5, 1),
('Scroll of Hold Monster', 'Paralyzes any creature.', 'Scroll', 400, 0.0, '', 0, 5, 1),
('Scroll of Scrying', 'Spy on distant targets.', 'Scroll', 400, 0.0, '', 0, 5, 1),
('Scroll of Disintegrate', 'Destroys target completely.', 'Scroll', 800, 0.0, '', 0, 6, 1),
('Scroll of Chain Lightning', 'Lightning jumps between targets.', 'Scroll', 800, 0.0, '', 0, 6, 1),
('Scroll of Time Stop', 'Freezes time briefly.', 'Scroll', 2000, 0.0, '', 0, 9, 1),

-- Tools (30 items)
('Thieves Tools', 'Pick locks and disarm traps.', 'Tool', 25, 1.0, '', 0, 1, 0),
('Rope (50 feet)', 'Strong hemp rope.', 'Tool', 2, 10.0, '', 0, 1, 0),
('Grappling Hook', 'For climbing and securing rope.', 'Tool', 5, 4.0, '', 0, 1, 0),
('Torch', 'Provides light in darkness.', 'Tool', 0, 1.0, '', 0, 1, 0),
('Lantern', 'Burns oil for bright light.', 'Tool', 5, 2.0, '', 0, 1, 0),
('Oil Flask', 'Fuel for lanterns or fire weapons.', 'Tool', 0, 1.0, '', 0, 1, 0),
('Bedroll', 'For comfortable rest while traveling.', 'Tool', 1, 7.0, '', 0, 1, 0),
('Blanket', 'Warmth during cold nights.', 'Tool', 0, 3.0, '', 0, 1, 0),
('Backpack', 'Carries equipment and supplies.', 'Tool', 2, 5.0, '', 0, 1, 0),
('Waterskin', 'Holds water for long journeys.', 'Tool', 2, 5.0, '', 0, 1, 0),
('Rations (1 day)', 'Preserved food for travel.', 'Tool', 2, 2.0, '', 0, 1, 0),
('Hempen Rope (50 feet)', 'Basic rope for various uses.', 'Tool', 2, 10.0, '', 0, 1, 0),
('Silk Rope (50 feet)', 'Lightweight, strong rope.', 'Tool', 10, 5.0, '', 0, 1, 0),
('Crowbar', 'For prying and breaking.', 'Tool', 5, 5.0, '', 0, 1, 0),
('Hammer', 'For construction and combat.', 'Tool', 2, 3.0, '1d4', 0, 1, 0),
('Pitons (10)', 'Spikes for climbing.', 'Tool', 0, 2.5, '', 0, 1, 0),
('Block and Tackle', 'Pulley system for heavy lifting.', 'Tool', 5, 5.0, '', 0, 1, 0),
('Chain (10 feet)', 'Heavy metal chain.', 'Tool', 5, 10.0, '', 0, 1, 0),
('Manacles', 'Shackles for prisoners.', 'Tool', 15, 6.0, '', 0, 1, 0),
('Mirror (steel)', 'Polished metal mirror.', 'Tool', 5, 0.5, '', 0, 1, 0),
('Shovel', 'For digging and construction.', 'Tool', 5, 5.0, '', 0, 1, 0),
('Tent (two-person)', 'Portable shelter.', 'Tool', 10, 20.0, '', 0, 1, 0),
('Tinderbox', 'For starting fires.', 'Tool', 0, 1.0, '', 0, 1, 0),
('Whetstone', 'For sharpening blades.', 'Tool', 0, 1.0, '', 0, 1, 0),
('Magnifying Glass', 'For examining small details.', 'Tool', 100, 0.0, '', 0, 1, 0),
('Spyglass', 'For seeing distant objects.', 'Tool', 1000, 1.0, '', 0, 2, 0),
('Hourglass', 'For measuring time.', 'Tool', 25, 1.0, '', 0, 1, 0),
('Scale (merchants)', 'For weighing goods.', 'Tool', 5, 3.0, '', 0, 1, 0),
('Sealing Wax', 'For official documents.', 'Tool', 0, 0.0, '', 0, 1, 0),
('Signet Ring', 'Personal seal of authority.', 'Tool', 5, 0.0, '', 0, 1, 0),

-- Adventuring Gear (40 items)
('Boots of Speed', 'Doubles movement speed.', 'Adventuring Gear', 2000, 2.0, '', 0, 5, 1),
('Cloak of Elvenkind', 'Provides stealth and protection.', 'Adventuring Gear', 5000, 1.0, '', 0, 8, 1),
('Bag of Holding', 'Holds much more than it appears.', 'Adventuring Gear', 4000, 15.0, '', 0, 4, 1),
('Portable Hole', 'Creates extradimensional space.', 'Adventuring Gear', 20000, 0.0, '', 0, 12, 1),
('Rope of Climbing', 'Climbs on command.', 'Adventuring Gear', 2000, 3.0, '', 0, 5, 1),
('Boots of Elvenkind', 'Move silently through any terrain.', 'Adventuring Gear', 2500, 1.0, '', 0, 5, 1),
('Gloves of Missile Snaring', 'Catch projectiles from the air.', 'Adventuring Gear', 3000, 0.0, '', 0, 6, 1),
('Hat of Disguise', 'Change appearance at will.', 'Adventuring Gear', 5000, 0.0, '', 0, 8, 1),
('Immovable Rod', 'Becomes fixed in space when activated.', 'Adventuring Gear', 5000, 2.0, '', 0, 6, 1),
('Decanter of Endless Water', 'Produces unlimited fresh water.', 'Adventuring Gear', 8000, 2.0, '', 0, 7, 1),
('Alchemy Jug', 'Produces various liquids daily.', 'Adventuring Gear', 6000, 12.0, '', 0, 6, 1),
('Eversmoking Bottle', 'Creates clouds of thick smoke.', 'Adventuring Gear', 1000, 1.0, '', 0, 3, 1),
('Folding Boat', 'Transforms into full-sized boat.', 'Adventuring Gear', 10000, 4.0, '', 0, 8, 1),
('Hewards Handy Haversack', 'Magical backpack with extra space.', 'Adventuring Gear', 2000, 5.0, '', 0, 4, 1),
('Horseshoes of Speed', 'Double a mounts movement.', 'Adventuring Gear', 5000, 12.0, '', 0, 6, 1),
('Necklace of Adaptation', 'Breathe in any environment.', 'Adventuring Gear', 1500, 1.0, '', 0, 4, 1),
('Periapt of Health', 'Immunity to disease.', 'Adventuring Gear', 5000, 0.0, '', 0, 7, 1),
('Pipes of Haunting', 'Create fear in enemies.', 'Adventuring Gear', 6000, 2.0, '', 0, 5, 1),
('Ring of Jumping', 'Triple jumping distance.', 'Adventuring Gear', 2500, 0.0, '', 0, 4, 1),
('Ring of Swimming', 'Swim as fast as walking.', 'Adventuring Gear', 3000, 0.0, '', 0, 4, 1),
('Ring of Warmth', 'Resist cold damage and environments.', 'Adventuring Gear', 1000, 0.0, '', 0, 3, 1),
('Slippers of Spider Climbing', 'Walk on walls and ceilings.', 'Adventuring Gear', 5000, 0.5, '', 0, 6, 1),
('Winged Boots', 'Grant flight for short periods.', 'Adventuring Gear', 8000, 1.0, '', 0, 8, 1),
('Amulet of Health', 'Sets Constitution to 19.', 'Adventuring Gear', 8000, 1.0, '', 0, 8, 1),
('Belt of Giant Strength', 'Greatly increases Strength.', 'Adventuring Gear', 10000, 2.0, '', 0, 10, 1),
('Bracers of Archery', 'Improve ranged attack accuracy.', 'Adventuring Gear', 1500, 2.0, '', 0, 4, 1),
('Circlet of Blasting', 'Cast scorching ray spells.', 'Adventuring Gear', 1500, 0.0, '', 0, 4, 1),
('Cloak of the Manta Ray', 'Swim like a sea creature.', 'Adventuring Gear', 6000, 1.0, '', 0, 6, 1),
('Eyes of the Eagle', 'Incredible vision and perception.', 'Adventuring Gear', 2500, 0.0, '', 0, 5, 1),
('Gauntlets of Ogre Power', 'Increases Strength significantly.', 'Adventuring Gear', 8000, 2.0, '', 0, 8, 1),
('Headband of Intellect', 'Sets Intelligence to 19.', 'Adventuring Gear', 8000, 1.0, '', 0, 8, 1),
('Medallion of Thoughts', 'Read surface thoughts.', 'Adventuring Gear', 3000, 1.0, '', 0, 5, 1),
('Pearl of Power', 'Regain expended spell slots.', 'Adventuring Gear', 6000, 0.0, '', 0, 7, 1),
('Ring of Feather Falling', 'Never take falling damage.', 'Adventuring Gear', 2000, 0.0, '', 0, 4, 1),
('Ring of Free Action', 'Immunity to movement restrictions.', 'Adventuring Gear', 20000, 0.0, '', 0, 12, 1),
('Ring of Mind Shielding', 'Protect thoughts from detection.', 'Adventuring Gear', 16000, 0.0, '', 0, 10, 1),
('Ring of Protection', 'Bonus to AC and saving throws.', 'Adventuring Gear', 3500, 0.0, '', 0, 6, 1),
('Ring of Sustenance', 'No need for food or water.', 'Adventuring Gear', 2500, 0.0, '', 0, 5, 1),
('Stone of Good Luck', 'Bonus to ability checks and saves.', 'Adventuring Gear', 4000, 0.0, '', 0, 6, 1),
('Figurine of Wondrous Power', 'Summons a magical creature.', 'Adventuring Gear', 15000, 1.0, '', 0, 10, 1),

-- Food & Drink (30 items)
('Bread Loaf', 'Fresh baked bread.', 'Food', 0, 2.0, '', 0, 1, 0),
('Hard Cheese', 'Aged cheese that travels well.', 'Food', 0, 1.0, '', 0, 1, 0),
('Dried Meat', 'Preserved meat for long journeys.', 'Food', 1, 1.0, '', 0, 1, 0),
('Trail Rations', 'Mixed nuts, dried fruit, and meat.', 'Food', 2, 2.0, '', 0, 1, 0),
('Fresh Fruit', 'Apples, oranges, or seasonal fruit.', 'Food', 0, 1.0, '', 0, 1, 0),
('Vegetables', 'Fresh carrots, turnips, or cabbage.', 'Food', 0, 2.0, '', 0, 1, 0),
('Wine (bottle)', 'Fine vintage wine.', 'Food', 2, 1.5, '', 0, 1, 0),
('Ale (mug)', 'Common tavern ale.', 'Food', 0, 1.0, '', 0, 1, 0),
('Mead (bottle)', 'Honey wine from the north.', 'Food', 3, 1.5, '', 0, 1, 0),
('Water (pure)', 'Clean drinking water.', 'Food', 0, 8.0, '', 0, 1, 0),
('Tea Leaves', 'Dried leaves for brewing tea.', 'Food', 1, 0.1, '', 0, 1, 0),
('Coffee Beans', 'Roasted beans for brewing.', 'Food', 2, 0.5, '', 0, 1, 0),
('Honey (jar)', 'Sweet honey from mountain bees.', 'Food', 2, 1.0, '', 0, 1, 0),
('Salt (pouch)', 'Precious mineral for preserving food.', 'Food', 1, 0.5, '', 0, 1, 0),
('Spices (exotic)', 'Rare spices from distant lands.', 'Food', 10, 0.1, '', 0, 1, 0),
('Flour (sack)', 'Ground wheat for baking.', 'Food', 1, 20.0, '', 0, 1, 0),
('Sugar (refined)', 'Sweet crystalline substance.', 'Food', 5, 1.0, '', 0, 1, 0),
('Preserved Fish', 'Salted fish that keeps well.', 'Food', 2, 2.0, '', 0, 1, 0),
('Smoked Ham', 'Delicious cured meat.', 'Food', 5, 8.0, '', 0, 1, 0),
('Pickled Vegetables', 'Vegetables preserved in brine.', 'Food', 1, 3.0, '', 0, 1, 0),
('Dried Beans', 'Protein-rich legumes.', 'Food', 1, 5.0, '', 0, 1, 0),
('Oats (bag)', 'Grain for porridge or horse feed.', 'Food', 1, 10.0, '', 0, 1, 0),
('Barley (bag)', 'Grain for bread and brewing.', 'Food', 1, 12.0, '', 0, 1, 0),
('Rice (exotic)', 'Rare grain from eastern lands.', 'Food', 5, 8.0, '', 0, 1, 0),
('Luxury Chocolate', 'Rare sweet from tropical regions.', 'Food', 20, 0.5, '', 0, 1, 0),
('Healing Herbs', 'Medicinal plants for treating wounds.', 'Food', 5, 0.5, '', 0, 1, 1),
('Energy Biscuits', 'Magically nutritious crackers.', 'Food', 10, 1.0, '', 0, 2, 1),
('Elven Waybread', 'Sustaining bread that never spoils.', 'Food', 50, 0.5, '', 0, 3, 1),
('Dwarven Ale', 'Potent brew that grants temporary strength.', 'Food', 15, 2.0, '', 0, 2, 1),
('Goodberry Wine', 'Magical wine that provides nourishment.', 'Food', 100, 1.0, '', 0, 4, 1),

-- Treasure (30 items)
('Gold Coin', 'Standard currency of the realm.', 'Treasure', 1, 0.02, '', 0, 1, 0),
('Silver Coin', 'Common currency worth 1/10 gold.', 'Treasure', 0, 0.02, '', 0, 1, 0),
('Copper Coin', 'Basic currency worth 1/100 gold.', 'Treasure', 0, 0.02, '', 0, 1, 0),
('Platinum Coin', 'Rare currency worth 10 gold.', 'Treasure', 10, 0.02, '', 0, 1, 0),
('Ruby (small)', 'A precious red gemstone.', 'Treasure', 100, 0.1, '', 0, 1, 0),
('Emerald (small)', 'A precious green gemstone.', 'Treasure', 100, 0.1, '', 0, 1, 0),
('Sapphire (small)', 'A precious blue gemstone.', 'Treasure', 100, 0.1, '', 0, 1, 0),
('Diamond (small)', 'The most precious gemstone.', 'Treasure', 500, 0.1, '', 0, 1, 0),
('Pearl (cultured)', 'A beautiful pearl from the sea.', 'Treasure', 50, 0.1, '', 0, 1, 0),
('Gold Ring (plain)', 'Simple band of precious metal.', 'Treasure', 25, 0.1, '', 0, 1, 0),
('Silver Necklace', 'Elegant jewelry piece.', 'Treasure', 50, 0.5, '', 0, 1, 0),
('Art Object (small)', 'Carved figurine or small painting.', 'Treasure', 200, 2.0, '', 0, 1, 0),
('Art Object (large)', 'Impressive statue or tapestry.', 'Treasure', 2000, 50.0, '', 0, 1, 0),
('Ancient Coin', 'Currency from a lost civilization.', 'Treasure', 50, 0.02, '', 0, 1, 0),
('Trade Bars (gold)', 'Standardized gold ingots.', 'Treasure', 500, 5.0, '', 0, 1, 0),
('Trade Bars (silver)', 'Standardized silver ingots.', 'Treasure', 50, 5.0, '', 0, 1, 0),
('Ornate Chalice', 'Ceremonial drinking cup.', 'Treasure', 300, 2.0, '', 0, 1, 0),
('Golden Crown', 'Symbol of royal authority.', 'Treasure', 5000, 3.0, '', 0, 1, 0),
('Ivory Tusk', 'Valuable carved elephant tusk.', 'Treasure', 1000, 20.0, '', 0, 1, 0),
('Rare Book', 'Ancient tome with valuable knowledge.', 'Treasure', 500, 3.0, '', 0, 1, 0),
('Map (treasure)', 'Shows location of hidden treasure.', 'Treasure', 1000, 0.1, '', 0, 1, 0),
('Crystal Orb', 'Perfect sphere of pure crystal.', 'Treasure', 800, 5.0, '', 0, 1, 1),
('Golden Statuette', 'Small figurine of precious metal.', 'Treasure', 1500, 2.0, '', 0, 1, 0),
('Jeweled Dagger', 'Ornamental weapon with gems.', 'Treasure', 2000, 1.0, '1d4', 0, 1, 0),
('Silk Tapestry', 'Intricately woven wall hanging.', 'Treasure', 1200, 8.0, '', 0, 1, 0),
('Spellbook (empty)', 'Blank tome for recording spells.', 'Treasure', 50, 3.0, '', 0, 1, 1),
('Alchemical Formula', 'Recipe for creating magical substances.', 'Treasure', 300, 0.1, '', 0, 1, 1),
('Star Chart', 'Map of celestial movements.', 'Treasure', 400, 1.0, '', 0, 1, 1),
('Religious Relic', 'Sacred object of divine power.', 'Treasure', 2500, 1.0, '', 0, 1, 1),
('Royal Seal', 'Official stamp of a kingdom.', 'Treasure', 3000, 0.5, '', 0, 1, 0);
